name: lab_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.7.0
  glass: ^1.0.1+1
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  http: ^0.13.6
  shared_preferences: ^2.2.0
  intl_phone_field: ^3.2.0
  intl: ^0.18.1
  dob_input_field: ^2.0.0


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf

